# Generated by Django 6.0.6 on 2026-07-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='users_app.interest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'Beginner / A0'), ('A1', 'Elementary / A1'), ('A2', 'Pre-Intermediate / A2'), ('B1', 'Intermediate / B1'), ('B2', 'Upper-Intermediate / B2'), ('C1', 'Advanced / C1'), ('C2', 'Proficiency / C2')], max_length=2)),
                ('learning_goal', models.CharField(blank=True, choices=[('travel', 'Travel'), ('work', 'Work'), ('study', 'Study'), ('movies', 'Movies and series'), ('relocation', 'Relocation'), ('communication', 'Communication'), ('exams', 'Exams'), ('other', 'Other')], max_length=30)),
                ('daily_minutes', models.PositiveSmallIntegerField(default=10)),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=30)),
                ('preferred_formats', models.JSONField(blank=True, default=list)),
                ('current_story_day', models.PositiveIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='users', through='users_app.UserInterest', to='users_app.interest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='users_app.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='userinterest',
            constraint=models.UniqueConstraint(fields=('user', 'interest'), name='unique_user_interest'),
        ),
    ]
