# Generated by Django 6.0.6 on 2026-07-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diagnostic_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_lessons_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weak_skills',
            field=models.JSONField(blank=True, default=list, help_text="Skills to focus on, e.g. ['listening', 'grammar']."),
        ),
    ]
