# Generated by Django 6.0.6 on 2026-07-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_userprofile_diagnostic_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Updated on every bot interaction (not just /start).', null=True),
        ),
    ]
