# Generated by Django 6.0.6 on 2026-07-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, choices=[('ecommerce', 'E-commerce'), ('it', 'IT / разработка'), ('hospitality', 'Отели / туризм'), ('food', 'Кафе / рестораны'), ('education', 'Образование'), ('psychology', 'Психология'), ('medicine', 'Медицина'), ('finance', 'Финансы'), ('marketing', 'Маркетинг'), ('other', 'Другое')], help_text='Professional sphere used to bias personalized content.', max_length=30),
        ),
    ]
