# Generated by Django 6.0.6 on 2026-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_userprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send daily training reminders via Telegram.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_setup_done',
            field=models.BooleanField(default=False, help_text='User was asked about notifications (do not re-prompt).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Local reminder time (uses timezone field).', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=50),
        ),
    ]
