# Generated by Django 6.0.6 on 2026-07-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('intro_text', models.TextField(blank=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sessions', to='content_app.storyepisode')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sessions', to='content_app.contenttheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sessions', to='users_app.userprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailySessionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('block_type', models.CharField(choices=[('story', 'Story'), ('vocabulary', 'Vocabulary'), ('quiz', 'Quiz'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('photo', 'Photo'), ('dialogue', 'Dialogue'), ('shadowing', 'Shadowing'), ('grammar', 'Grammar'), ('reflection', 'Reflection')], max_length=30)),
                ('skill', models.CharField(blank=True, choices=[('vocabulary', 'Vocabulary'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='study_app.dailysession')),
            ],
            options={
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_payload', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('detected_errors', models.JSONField(blank=True, default=list)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='study_app.dailysessionblock')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='study_app.dailysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users_app.userprofile')),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailysession',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_session_per_user_date'),
        ),
        migrations.AddConstraint(
            model_name='dailysessionblock',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_block_order_in_session'),
        ),
    ]
