# Generated by Django 6.0.6 on 2026-07-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_mediaasset_telegram_file_id_diagnosticitem_lesson_and_more'),
        ('study_app', '0001_initial'),
        ('users_app', '0002_userprofile_diagnostic_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('used_ai', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_attempts', to='content_app.lesson')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content_app.lessonstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_attempts', to='users_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_answered', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content_app.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='users_app.userprofile')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson_progress')],
            },
        ),
    ]
