# Generated by Django 6.0.6 on 2026-07-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('personality', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='media_assets/')),
                ('source_url', models.URLField(blank=True)),
                ('license_name', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.CharField(max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrases', to='content_app.contenttheme')),
            ],
            options={
                'ordering': ['english_text'],
            },
        ),
        migrations.CreateModel(
            name='StoryEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=2)),
                ('short_summary', models.TextField(blank=True)),
                ('story_text', models.TextField()),
                ('choices', models.JSONField(blank=True, default=list)),
                ('target_words', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content_app.storyarc')),
                ('characters', models.ManyToManyField(blank=True, related_name='episodes', to='content_app.character')),
                ('target_phrases', models.ManyToManyField(blank=True, related_name='episodes', to='content_app.phrase')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='content_app.contenttheme')),
            ],
            options={
                'ordering': ['arc', 'episode_number'],
                'constraints': [models.UniqueConstraint(fields=('arc', 'episode_number'), name='unique_episode_in_arc')],
            },
        ),
    ]
