# Generated by Django 6.0.6 on 2026-07-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text='Cached Telegram file_id to re-send media without re-uploading.', max_length=500),
        ),
        migrations.CreateModel(
            name='DiagnosticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2')], max_length=5)),
                ('skill', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation'), ('mixed', 'Mixed')], default='grammar', max_length=20)),
                ('item_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_gap', 'Fill the gap'), ('translation_ru_en', 'Translation RU → EN'), ('listening', 'Listening (audio → choice)'), ('speaking', 'Speaking (voice)')], max_length=30)),
                ('prompt', models.TextField(help_text='Question text (may be in Russian).')),
                ('options', models.JSONField(blank=True, default=list, help_text="Answer options for choice types, e.g. ['drink', 'drinks', 'drinking'].")),
                ('correct', models.JSONField(blank=True, default=list, help_text="Accepted answers, e.g. ['drinks'] or ['i was at home yesterday'].")),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Must-have keywords for translation/speaking checks.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('audio', models.ForeignKey(blank=True, help_text='Audio for listening / target phrase for speaking items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_items', to='content_app.mediaasset')),
            ],
            options={
                'ordering': ['level', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2')], default='a1', max_length=5)),
                ('intro_text', models.TextField(blank=True)),
                ('outro_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_trial', models.BooleanField(default=False, help_text='Available for free (trial).')),
                ('is_published', models.BooleanField(default=False)),
                ('estimated_minutes', models.PositiveIntegerField(default=8)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='content_app.character')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_covers', to='content_app.mediaasset')),
                ('story_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='content_app.storyepisode')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='content_app.contenttheme')),
            ],
            options={
                'ordering': ['level', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_type', models.CharField(choices=[('hook', 'Hook'), ('story', 'Story scene'), ('image', 'Image'), ('gif', 'GIF'), ('audio', 'Audio'), ('video', 'Video'), ('vocabulary', 'Vocabulary cards'), ('grammar_note', 'Grammar note'), ('dialogue', 'Scripted dialogue'), ('exercise', 'Exercise'), ('speaking', 'Speaking (voice)'), ('ai_dialogue', 'Free AI dialogue'), ('reflection', 'Reflection'), ('reward', 'Reward'), ('cliffhanger', 'Cliffhanger')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('skill', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('content', models.JSONField(blank=True, default=dict, help_text="Structured data. For interactive steps: {'exercise_type','options','correct','keywords','hints','explanation','ai_fallback','ai_check_prompt','points','target'}.")),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_optional', models.BooleanField(default=False)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_steps', to='content_app.character')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content_app.lesson')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_steps', to='content_app.mediaasset')),
            ],
            options={
                'ordering': ['lesson', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'order'), name='unique_step_order_in_lesson')],
            },
        ),
    ]
