# Generated by Django 6.0.6 on 2026-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_unit_lesson_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('topic', models.CharField(help_text='Topic group, e.g. «Просьбы».', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2')], default='a1', max_length=5)),
                ('summary_ru', models.TextField(blank=True)),
                ('table', models.JSONField(blank=True, default=dict)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('tip_ru', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'topic', 'order', 'id'],
            },
        ),
    ]
