# Generated by Django 6.0.6 on 2026-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_charactermedia_source_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermedia',
            name='source_path',
            field=models.CharField(blank=True, help_text='Relative path under media/spirit/ (for sync & replace)', max_length=255),
        ),
    ]
