"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default


# -------------------------------------------------------------------
# Telegram
# -------------------------------------------------------------------
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_PAYMENT_PROVIDER_TOKEN = os.getenv('TELEGRAM_PAYMENT_PROVIDER_TOKEN', '')
# If api.telegram.org is blocked from your VPS (common on some RU DCs), set e.g.:
# TELEGRAM_PROXY=socks5://127.0.0.1:1080  or  http://user:pass@host:port
TELEGRAM_PROXY = os.getenv('TELEGRAM_PROXY', '').strip()

# -------------------------------------------------------------------
# Subscription / billing (single plan)
# -------------------------------------------------------------------
# One plan: 390 RUB for 30 days, no auto-renewal.
SUBSCRIPTION_PRICE_RUB = env_int('SUBSCRIPTION_PRICE_RUB', 590)
SUBSCRIPTION_PRICE_KOPEKS = SUBSCRIPTION_PRICE_RUB * 100
SUBSCRIPTION_DAYS = env_int('SUBSCRIPTION_DAYS', 30)
TRIAL_LESSONS_LIMIT = env_int('TRIAL_LESSONS_LIMIT', 2)
TRIAL_DAYS = env_int('TRIAL_DAYS', 2)

# 'mock'  -> instant activation for development / YooKassa screenshots
# 'live'  -> real payment via YooKassa (enable after store moderation)
# To go live: set PAYMENT_MODE=live and TELEGRAM_PAYMENT_PROVIDER_TOKEN
# (the YooKassa provider token from @BotFather → Payments). Nothing else in the
# bot needs to change; buy_subscription() already sends a real Telegram invoice.
PAYMENT_MODE = os.getenv('PAYMENT_MODE', 'mock')

# YooKassa (filled in after the store is approved)
YOOKASSA_SHOP_ID = os.getenv('YOOKASSA_SHOP_ID', '')
YOOKASSA_SECRET_KEY = os.getenv('YOOKASSA_SECRET_KEY', '')

# Backwards-compat with legacy bot_app while it is being retired.
MONTHLY_SUBSCRIPTION_PRICE_KOPEKS = SUBSCRIPTION_PRICE_KOPEKS

# -------------------------------------------------------------------
# AI provider (answer checking, hints, AI dialogue) — economical by design
# -------------------------------------------------------------------
# 'openai' | 'openai_compatible' (any OpenAI-style gateway) | 'mock'.
AI_PROVIDER = os.getenv(
    'AI_PROVIDER',
    'openai' if os.getenv('OPENAI_API_KEY') else 'mock',
)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')
# Optional tiered models (fall back to OPENAI_MODEL). Cheap = simple checks,
# advanced = harder writing/dialogue. Lets us spend less on trivial tasks.
OPENAI_CHEAP_MODEL = os.getenv('OPENAI_CHEAP_MODEL', OPENAI_MODEL)
OPENAI_ADVANCED_MODEL = os.getenv('OPENAI_ADVANCED_MODEL', OPENAI_MODEL)
# Base URL of the OpenAI-compatible endpoint (proxy/gateway friendly).
OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL', 'https://api.openai.com/v1')

# Request/behaviour tuning (read from .env with these exact names).
AI_TIMEOUT_SECONDS = env_int('AI_TIMEOUT_SECONDS', 30)
AI_MAX_OUTPUT_TOKENS = env_int('AI_MAX_OUTPUT_TOKENS', 400)
# How many recent chat messages to keep in an AI dialogue window.
AI_HISTORY_MESSAGES = env_int('AI_HISTORY_MESSAGES', 8)

# Token-economy guardrail (internal; not required in .env).
AI_DAILY_CALL_LIMIT_PER_USER = env_int('AI_DAILY_CALL_LIMIT_PER_USER', 40)

# -------------------------------------------------------------------
# Text-to-speech (voicing English words / phrases for listening practice)
# -------------------------------------------------------------------
TTS_ENABLED = env_bool('TTS_ENABLED', True)
# 'openai' -> OpenAI-compatible /audio/speech via OPENAI_* (AITUNNEL: gpt-4o-mini-tts)
# 'edge'   -> free Microsoft Edge neural voices (fallback, no key)
# 'mock'   -> disabled / offline
_def_openai = bool(os.getenv('OPENAI_API_KEY', '').strip())
TTS_PROVIDER = os.getenv(
    'TTS_PROVIDER',
    'openai' if _def_openai else 'edge',
)
TTS_VOICE = os.getenv('TTS_VOICE', 'en-US-AriaNeural')
TTS_TIMEOUT_SECONDS = env_int('TTS_TIMEOUT_SECONDS', 30)
# AITUNNEL slug: gpt-4o-mini-tts (~120 ₽/1M chars) | tts-1 | tts-1-hd
OPENAI_TTS_MODEL = os.getenv('OPENAI_TTS_MODEL', 'gpt-4o-mini-tts')
OPENAI_TTS_VOICE = os.getenv('OPENAI_TTS_VOICE', 'alloy')

# -------------------------------------------------------------------
# Speech-to-text (voice answers) — Whisper via OPENAI_* (AITUNNEL) or Yandex fallback
# -------------------------------------------------------------------
STT_PROVIDER = os.getenv(
    'STT_PROVIDER',
    'whisper' if _def_openai else (
        'yandex' if os.getenv('YANDEX_SPEECHKIT_API_KEY') else 'mock'
    ),
)
# Tutor voice: Whisper via OPENAI_* proxy (e.g. AITUNNEL) when key is set.
STT_TUTOR_PROVIDER = os.getenv('STT_TUTOR_PROVIDER', 'auto')
# Use Yandex STT only when Whisper RU pass is weak (off = AITUNNEL-only stack).
STT_YANDEX_FALLBACK = env_bool('STT_YANDEX_FALLBACK', False)
OPENAI_WHISPER_MODEL = os.getenv('OPENAI_WHISPER_MODEL', 'whisper-large-v3-turbo')
OPENAI_WHISPER_FALLBACK_MODELS = os.getenv(
    'OPENAI_WHISPER_FALLBACK_MODELS',
    'whisper-large-v3,whisper-1',
)
OPENAI_STT_TIMEOUT_SECONDS = env_int('OPENAI_STT_TIMEOUT_SECONDS', 45)
# Voice mentor limits (see docs/TARIFFS.md)
VOICE_MAX_DURATION_SECONDS = env_int('VOICE_MAX_DURATION_SECONDS', 120)
VOICE_MAX_PER_HOUR = env_int('VOICE_MAX_PER_HOUR', 20)
YANDEX_SPEECHKIT_API_KEY = os.getenv('YANDEX_SPEECHKIT_API_KEY', '')
YANDEX_FOLDER_ID = os.getenv('YANDEX_FOLDER_ID', '')
YANDEX_STT_TIMEOUT_SECONDS = env_int('YANDEX_STT_TIMEOUT_SECONDS', 20)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-eyqe^fp0m4jx!&pd76z2xa=kqg6b_!i^*m(q=q&_m4-0)5dd^q',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Existing project apps
    'core',
    'learning',

    # Product apps
    'users_app',
    'content_app',
    'study_app',
    'progress_app',
    'gamification_app',
    'billing_app',
    'telegram_app',
    'ai_app',

    # Legacy (being retired; kept installed until data migration is done)
    'bot_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'Europe/Moscow')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media (uploaded lesson media: images, audio, video, GIFs)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

