# Generated by Django 6.0.6 on 2026-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100, verbose_name='Слово на английском')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('example', models.TextField(blank=True, verbose_name='Пример использования')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='medium', max_length=20, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['english'],
            },
        ),
    ]
