"""Built-in A1–C1 starter corpus (EN + RU). Extend via learning/data/word_bank/*.json."""

from __future__ import annotations

from .normalize import word_slug

# (english, translation, example_en, example_ru, pos, topics)
Row = tuple[str, str, str, str, str, tuple[str, ...]]


def _pack(level: str, items: list[tuple]) -> list[dict]:
    out = []
    for item in items:
        en, ru = item[0], item[1]
        ex = item[2] if len(item) > 2 else ''
        ex_ru = item[3] if len(item) > 3 else ''
        pos = item[4] if len(item) > 4 else ''
        topics = list(item[5]) if len(item) > 5 else []
        out.append({
            'slug': word_slug(en),
            'english': en,
            'translation': ru,
            'example': ex,
            'example_ru': ex_ru,
            'cefr_level': level,
            'part_of_speech': pos,
            'topics': topics,
        })
    return out


A1: list[tuple] = [
    ('hello', 'привет', 'Hello!', 'Привет!', 'interj', ('greetings',)),
    ('hi', 'привет', 'Hi there!', 'Привет!', 'interj', ('greetings',)),
    ('goodbye', 'до свидания', 'Goodbye!', 'До свидания!', 'interj', ('greetings',)),
    ('please', 'пожалуйста', 'Water, please.', 'Воды, пожалуйста.', 'adv', ()),
    ('thank you', 'спасибо', 'Thank you very much.', 'Большое спасибо.', 'phrase', ()),
    ('sorry', 'извините', 'Sorry, I am late.', 'Извините, я опоздал.', 'adj', ()),
    ('yes', 'да', 'Yes, please.', 'Да, пожалуйста.', 'adv', ()),
    ('no', 'нет', 'No, thank you.', 'Нет, спасибо.', 'adv', ()),
    ('name', 'имя', 'My name is Anna.', 'Меня зовут Анна.', 'noun', ('people',)),
    ('friend', 'друг', 'She is my friend.', 'Она моя подруга.', 'noun', ('people',)),
    ('family', 'семья', 'I love my family.', 'Я люблю свою семью.', 'noun', ('people',)),
    ('mother', 'мама', 'My mother is kind.', 'Моя мама добрая.', 'noun', ('people',)),
    ('father', 'папа', 'My father works a lot.', 'Мой папа много работает.', 'noun', ('people',)),
    ('child', 'ребёнок', 'The child is happy.', 'Ребёнок счастлив.', 'noun', ('people',)),
    ('man', 'мужчина', 'The man is tall.', 'Мужчина высокий.', 'noun', ('people',)),
    ('woman', 'женщина', 'The woman is a doctor.', 'Женщина — врач.', 'noun', ('people',)),
    ('student', 'студент', 'I am a student.', 'Я студент.', 'noun', ('education',)),
    ('teacher', 'учитель', 'She is a teacher.', 'Она учитель.', 'noun', ('education',)),
    ('day', 'день', 'Have a nice day!', 'Хорошего дня!', 'noun', ('time',)),
    ('week', 'неделя', 'See you next week.', 'Увидимся на следующей неделе.', 'noun', ('time',)),
    ('month', 'месяц', 'Next month I travel.', 'В следующем месяце я поеду.', 'noun', ('time',)),
    ('year', 'год', 'Happy New Year!', 'С Новым годом!', 'noun', ('time',)),
    ('today', 'сегодня', 'I am busy today.', 'Я занят сегодня.', 'adv', ('time',)),
    ('tomorrow', 'завтра', 'See you tomorrow.', 'До завтра.', 'adv', ('time',)),
    ('morning', 'утро', 'Good morning!', 'Доброе утро!', 'noun', ('time',)),
    ('evening', 'вечер', 'Good evening!', 'Добрый вечер!', 'noun', ('time',)),
    ('night', 'ночь', 'Good night!', 'Спокойной ночи!', 'noun', ('time',)),
    ('time', 'время', 'What time is it?', 'Который час?', 'noun', ('time',)),
    ('home', 'дом', 'I am at home.', 'Я дома.', 'noun', ('places',)),
    ('house', 'дом', 'This is my house.', 'Это мой дом.', 'noun', ('places',)),
    ('room', 'комната', 'My room is small.', 'Моя комната маленькая.', 'noun', ('places',)),
    ('door', 'дверь', 'Close the door, please.', 'Закрой дверь, пожалуйста.', 'noun', ('places',)),
    ('food', 'еда', 'The food is good.', 'Еда хорошая.', 'noun', ('food',)),
    ('water', 'вода', 'Can I have water?', 'Можно воды?', 'noun', ('food',)),
    ('coffee', 'кофе', 'I love coffee.', 'Я люблю кофе.', 'noun', ('food',)),
    ('tea', 'чай', 'A cup of tea, please.', 'Чашку чая, пожалуйста.', 'noun', ('food',)),
    ('milk', 'молоко', 'I drink milk.', 'Я пью молоко.', 'noun', ('food',)),
    ('bread', 'хлеб', 'Fresh bread smells good.', 'Свежий хлеб приятно пахнет.', 'noun', ('food',)),
    ('apple', 'яблоко', 'An apple a day.', 'Яблоко в день.', 'noun', ('food',)),
    ('eat', 'есть', 'I eat breakfast at eight.', 'Я завтракаю в восемь.', 'verb', ('food',)),
    ('drink', 'пить', 'I drink tea.', 'Я пью чай.', 'verb', ('food',)),
    ('go', 'идти / ехать', 'I go to work.', 'Я иду на работу.', 'verb', ()),
    ('come', 'приходить', 'Come here, please.', 'Иди сюда, пожалуйста.', 'verb', ()),
    ('work', 'работать', 'I work from home.', 'Я работаю из дома.', 'verb', ('work',)),
    ('study', 'учиться', 'I study English.', 'Я учу английский.', 'verb', ('education',)),
    ('read', 'читать', 'I read every day.', 'Я читаю каждый день.', 'verb', ()),
    ('write', 'писать', 'Write your name.', 'Напиши своё имя.', 'verb', ()),
    ('speak', 'говорить', 'I speak English.', 'Я говорю по-английски.', 'verb', ()),
    ('listen', 'слушать', 'Listen carefully.', 'Слушай внимательно.', 'verb', ()),
    ('see', 'видеть', 'I see you.', 'Я тебя вижу.', 'verb', ()),
    ('know', 'знать', 'I know the answer.', 'Я знаю ответ.', 'verb', ()),
    ('want', 'хотеть', 'I want coffee.', 'Я хочу кофе.', 'verb', ()),
    ('like', 'нравиться', 'I like tea.', 'Мне нравится чай.', 'verb', ()),
    ('love', 'любить', 'I love my job.', 'Я люблю свою работу.', 'verb', ()),
    ('have', 'иметь', 'I have a cat.', 'У меня есть кот.', 'verb', ()),
    ('good', 'хороший', 'Good idea!', 'Хорошая идея!', 'adj', ()),
    ('bad', 'плохой', 'Bad weather today.', 'Сегодня плохая погода.', 'adj', ()),
    ('big', 'большой', 'A big city.', 'Большой город.', 'adj', ()),
    ('small', 'маленький', 'A small room.', 'Маленькая комната.', 'adj', ()),
    ('new', 'новый', 'A new phone.', 'Новый телефон.', 'adj', ()),
    ('old', 'старый', 'An old book.', 'Старая книга.', 'adj', ()),
    ('hot', 'горячий', 'Hot coffee.', 'Горячий кофе.', 'adj', ()),
    ('cold', 'холодный', 'Cold water.', 'Холодная вода.', 'adj', ()),
    ('happy', 'счастливый', 'I am happy.', 'Я счастлив.', 'adj', ()),
    ('here', 'здесь', 'I am here.', 'Я здесь.', 'adv', ()),
    ('there', 'там', 'The shop is there.', 'Магазин там.', 'adv', ()),
    ('where', 'где', 'Where are you?', 'Где ты?', 'adv', ()),
    ('what', 'что', 'What is this?', 'Что это?', 'pron', ()),
    ('who', 'кто', 'Who is she?', 'Кто она?', 'pron', ()),
    ('how', 'как', 'How are you?', 'Как дела?', 'adv', ()),
    ('very', 'очень', 'Very good!', 'Очень хорошо!', 'adv', ()),
    ('and', 'и', 'Tea and coffee.', 'Чай и кофе.', 'conj', ()),
    ('but', 'но', 'Small but cozy.', 'Маленький, но уютный.', 'conj', ()),
]

A2: list[tuple] = [
    ('menu', 'меню', 'Can I see the menu?', 'Можно меню?', 'noun', ('food',)),
    ('order', 'заказ / заказывать', 'I would like to order.', 'Я бы хотел заказать.', 'noun', ('food',)),
    ('bill', 'счёт', 'Can I have the bill?', 'Можно счёт?', 'noun', ('food',)),
    ('delicious', 'вкусный', 'It was delicious!', 'Было очень вкусно!', 'adj', ('food',)),
    ('restaurant', 'ресторан', 'This restaurant is nice.', 'Этот ресторан классный.', 'noun', ('food',)),
    ('breakfast', 'завтрак', 'Breakfast is at eight.', 'Завтрак в восемь.', 'noun', ('food',)),
    ('lunch', 'обед', 'Let us have lunch.', 'Давай пообедаем.', 'noun', ('food',)),
    ('dinner', 'ужин', 'Dinner is ready.', 'Ужин готов.', 'noun', ('food',)),
    ('seat', 'место', 'Is this seat taken?', 'Это место занято?', 'noun', ('travel',)),
    ('flight', 'рейс', 'Our flight is delayed.', 'Наш рейс задержали.', 'noun', ('travel',)),
    ('trip', 'поездка', 'Have a nice trip!', 'Хорошей поездки!', 'noun', ('travel',)),
    ('ticket', 'билет', 'I need a ticket.', 'Мне нужен билет.', 'noun', ('travel',)),
    ('passport', 'паспорт', 'Here is my passport.', 'Вот мой паспорт.', 'noun', ('travel',)),
    ('airport', 'аэропорт', 'The airport is far.', 'Аэропорт далеко.', 'noun', ('travel',)),
    ('hotel', 'отель', 'We stay at a hotel.', 'Мы останавливаемся в отеле.', 'noun', ('travel',)),
    ('reservation', 'бронь', 'I have a reservation.', 'У меня бронь.', 'noun', ('travel',)),
    ('check in', 'заселиться', "I'd like to check in.", 'Я бы хотел заселиться.', 'verb', ('travel',)),
    ('key', 'ключ', 'Here is your key.', 'Вот ваш ключ.', 'noun', ('travel',)),
    ('lift', 'лифт', 'The lift is on the left.', 'Лифт слева.', 'noun', ('travel',)),
    ('nice to meet you', 'приятно познакомиться', 'Nice to meet you!', 'Приятно познакомиться!', 'phrase', ('communication',)),
    ('from', 'из', 'I am from Russia.', 'Я из России.', 'prep', ()),
    ('live', 'жить', 'I live in Moscow.', 'Я живу в Москве.', 'verb', ()),
    ('job', 'работа', 'I love my job.', 'Я люблю свою работу.', 'noun', ('work',)),
    ('colleague', 'коллега', 'My colleague is helpful.', 'Мой коллега отзывчивый.', 'noun', ('work',)),
    ('office', 'офис', 'I work in an office.', 'Я работаю в офисе.', 'noun', ('work',)),
    ('meeting', 'встреча', 'We have a meeting at ten.', 'У нас встреча в десять.', 'noun', ('work',)),
    ('email', 'электронная почта', 'Send me an email.', 'Пришли мне письмо.', 'noun', ('work',)),
    ('phone', 'телефон', 'My phone is off.', 'Мой телефон выключен.', 'noun', ()),
    ('busy', 'занятой', 'I am busy today.', 'Я занят сегодня.', 'adj', ()),
    ('free', 'свободный', 'Are you free tonight?', 'Ты свободен сегодня вечером?', 'adj', ()),
    ('weather', 'погода', 'Nice weather today.', 'Сегодня хорошая погода.', 'noun', ()),
    ('rain', 'дождь', 'It is raining.', 'Идёт дождь.', 'noun', ()),
    ('sunny', 'солнечный', 'It is sunny.', 'Солнечно.', 'adj', ()),
    ('travel', 'путешествовать', 'I love to travel.', 'Я люблю путешествовать.', 'verb', ('travel',)),
    ('visit', 'посещать', 'I visit my parents.', 'Я навещаю родителей.', 'verb', ()),
    ('often', 'часто', 'I often work late.', 'Я часто работаю допоздна.', 'adv', ()),
    ('sometimes', 'иногда', 'Sometimes I cook.', 'Иногда я готовлю.', 'adv', ()),
    ('always', 'всегда', 'I always drink coffee.', 'Я всегда пью кофе.', 'adv', ()),
    ('never', 'никогда', 'I never give up.', 'Я никогда не сдаюсь.', 'adv', ()),
    ('because', 'потому что', 'I stayed because I was tired.', 'Я остался, потому что устал.', 'conj', ()),
    ('before', 'до / перед', 'Before the meeting.', 'Перед встречей.', 'prep', ()),
    ('after', 'после', 'After work I rest.', 'После работы я отдыхаю.', 'prep', ()),
    ('early', 'рано', 'I wake up early.', 'Я рано просыпаюсь.', 'adv', ()),
    ('late', 'поздно', 'Sorry, I am late.', 'Извините, я опоздал.', 'adv', ()),
    ('problem', 'проблема', 'No problem!', 'Без проблем!', 'noun', ()),
    ('help', 'помощь / помогать', 'Can you help me?', 'Можешь помочь?', 'noun', ()),
    ('idea', 'идея', 'Good idea!', 'Хорошая идея!', 'noun', ()),
    ('question', 'вопрос', 'I have a question.', 'У меня вопрос.', 'noun', ()),
    ('answer', 'ответ', 'That is the answer.', 'Это ответ.', 'noun', ()),
    ('explain', 'объяснять', 'Can you explain?', 'Можешь объяснить?', 'verb', ()),
    ('understand', 'понимать', 'I understand you.', 'Я тебя понимаю.', 'verb', ()),
    ('remember', 'помнить', 'I remember you.', 'Я тебя помню.', 'verb', ()),
    ('forget', 'забывать', 'Do not forget your passport.', 'Не забудь паспорт.', 'verb', ()),
    ('try', 'пытаться / пробовать', 'Try again.', 'Попробуй ещё раз.', 'verb', ()),
    ('start', 'начинать', 'Let us start.', 'Давай начнём.', 'verb', ()),
    ('finish', 'заканчивать', 'I finish at six.', 'Я заканчиваю в шесть.', 'verb', ()),
    ('wait', 'ждать', 'Please wait.', 'Подождите, пожалуйста.', 'verb', ()),
    ('buy', 'покупать', 'I want to buy tea.', 'Я хочу купить чай.', 'verb', ()),
    ('pay', 'платить', 'Can I pay by card?', 'Можно картой?', 'verb', ()),
    ('cheap', 'дешёвый', 'It is cheap.', 'Это дёшево.', 'adj', ()),
    ('expensive', 'дорогой', 'It is too expensive.', 'Это слишком дорого.', 'adj', ()),
]

B1: list[tuple] = [
    ('team', 'команда', 'I work in a small team.', 'Я работаю в небольшой команде.', 'noun', ('work',)),
    ('project', 'проект', 'I am on a new project.', 'Я на новом проекте.', 'noun', ('work',)),
    ('role', 'роль', 'What is your role?', 'Какая у тебя роль?', 'noun', ('work',)),
    ('deadline', 'дедлайн', 'The deadline is Friday.', 'Дедлайн — пятница.', 'noun', ('work',)),
    ('update', 'апдейт, отчёт', 'Here is my quick update.', 'Краткий апдейт.', 'noun', ('work',)),
    ('feedback', 'обратная связь', 'I need feedback.', 'Мне нужна обратная связь.', 'noun', ('work',)),
    ('on track', 'по плану', 'We are on track.', 'Мы по плану.', 'phrase', ('work',)),
    ('blocker', 'блокер', 'One blocker for now.', 'Пока один блокер.', 'noun', ('work',)),
    ('stand-up', 'стендап', 'We have a stand-up at ten.', 'Стендап в десять.', 'noun', ('work',)),
    ('schedule', 'расписание', 'Check the schedule.', 'Проверь расписание.', 'noun', ('work',)),
    ('discuss', 'обсуждать', 'Let us discuss it.', 'Давай обсудим.', 'verb', ()),
    ('decide', 'решать', 'We need to decide.', 'Нам нужно решить.', 'verb', ()),
    ('suggest', 'предлагать', 'I suggest a break.', 'Предлагаю перерыв.', 'verb', ()),
    ('agree', 'соглашаться', 'I agree with you.', 'Я согласен с тобой.', 'verb', ()),
    ('disagree', 'не соглашаться', 'I disagree politely.', 'Я вежливо не согласен.', 'verb', ()),
    ('improve', 'улучшать', 'We can improve this.', 'Мы можем это улучшить.', 'verb', ()),
    ('achieve', 'достигать', 'We achieved the goal.', 'Мы достигли цели.', 'verb', ()),
    ('goal', 'цель', 'What is the goal?', 'Какая цель?', 'noun', ()),
    ('challenge', 'вызов / сложность', 'It is a challenge.', 'Это вызов.', 'noun', ()),
    ('experience', 'опыт', 'I have five years of experience.', 'У меня пять лет опыта.', 'noun', ()),
    ('skill', 'навык', 'Communication is a key skill.', 'Коммуникация — ключевой навык.', 'noun', ()),
    ('confident', 'уверенный', 'I feel confident.', 'Я чувствую уверенность.', 'adj', ()),
    ('nervous', 'нервничать', 'I am nervous before calls.', 'Я нервничаю перед созвонами.', 'adj', ()),
    ('appointment', 'встреча / запись', 'I have an appointment.', 'У меня запись.', 'noun', ()),
    ('cancel', 'отменять', 'I had to cancel.', 'Мне пришлось отменить.', 'verb', ()),
    ('confirm', 'подтверждать', 'Please confirm the time.', 'Подтверди время, пожалуйста.', 'verb', ()),
    ('available', 'доступный', 'Are you available at three?', 'Ты свободен в три?', 'adj', ()),
    ('postpone', 'переносить', 'Can we postpone it?', 'Можем перенести?', 'verb', ()),
    ('negotiate', 'договариваться', 'We need to negotiate.', 'Нам нужно договориться.', 'verb', ()),
    ('budget', 'бюджет', 'It fits the budget.', 'Укладывается в бюджет.', 'noun', ()),
    ('invest', 'инвестировать', 'We invest in training.', 'Мы инвестируем в обучение.', 'verb', ()),
    ('customer', 'клиент', 'The customer is happy.', 'Клиент доволен.', 'noun', ()),
    ('service', 'услуга / сервис', 'Great service!', 'Отличный сервис!', 'noun', ()),
    ('complaint', 'жалоба', 'We got a complaint.', 'Поступила жалоба.', 'noun', ()),
    ('solution', 'решение', 'We found a solution.', 'Мы нашли решение.', 'noun', ()),
    ('efficient', 'эффективный', 'An efficient process.', 'Эффективный процесс.', 'adj', ()),
    ('reliable', 'надёжный', 'A reliable partner.', 'Надёжный партнёр.', 'adj', ()),
    ('responsible', 'ответственный', 'Who is responsible?', 'Кто ответственный?', 'adj', ()),
    ('priority', 'приоритет', 'That is a priority.', 'Это приоритет.', 'noun', ()),
    ('progress', 'прогресс', 'Good progress so far.', 'Хороший прогресс пока.', 'noun', ()),
    ('review', 'ревью / проверка', 'Please review the draft.', 'Проверь черновик.', 'noun', ()),
    ('draft', 'черновик', 'Send me the draft.', 'Пришли черновик.', 'noun', ()),
    ('launch', 'запуск', 'The launch is next week.', 'Запуск на следующей неделе.', 'noun', ()),
    ('feature', 'функция', 'We shipped a new feature.', 'Мы выпустили новую функцию.', 'noun', ()),
    ('bug', 'баг', 'We fixed a bug.', 'Мы исправили баг.', 'noun', ()),
    ('testing', 'тестирование', 'Testing takes time.', 'Тестирование занимает время.', 'noun', ()),
    ('deploy', 'деплой', 'We deploy on Friday.', 'Деплоим в пятницу.', 'verb', ()),
    ('stakeholder', 'стейкхолдер', 'Update the stakeholders.', 'Обнови стейкхолдеров.', 'noun', ()),
    ('estimate', 'оценка / оценивать', 'Give me an estimate.', 'Дай оценку.', 'noun', ()),
    ('scope', 'объём работ', 'That is out of scope.', 'Это вне объёма.', 'noun', ()),
    ('risk', 'риск', 'There is a risk.', 'Есть риск.', 'noun', ()),
    ('mitigate', 'смягчать', 'We mitigated the risk.', 'Мы смягчили риск.', 'verb', ()),
    ('align', 'согласовывать', 'Let us align on goals.', 'Давай согласуем цели.', 'verb', ()),
    ('clarify', 'уточнять', 'Can you clarify?', 'Можешь уточнить?', 'verb', ()),
    ('follow up', 'продолжить / напомнить', 'I will follow up tomorrow.', 'Напомню завтра.', 'verb', ()),
]

B2: list[tuple] = [
    ('compelling', 'убедительный', 'A compelling story.', 'Убедительная история.', 'adj', ()),
    ('nuance', 'нюанс', 'There is a nuance here.', 'Тут есть нюанс.', 'noun', ()),
    ('ambiguous', 'двусмысленный', 'The message was ambiguous.', 'Сообщение было двусмысленным.', 'adj', ()),
    ('assertive', 'уверенный / напористый', 'Be assertive but polite.', 'Будь уверенным, но вежливым.', 'adj', ()),
    ('concise', 'лаконичный', 'Keep it concise.', 'Будь лаконичным.', 'adj', ()),
    ('coherent', 'связный', 'A coherent argument.', 'Связный аргумент.', 'adj', ()),
    ('contradict', 'противоречить', 'The facts contradict it.', 'Факты этому противоречат.', 'verb', ()),
    ('criteria', 'критерии', 'What are the criteria?', 'Какие критерии?', 'noun', ()),
    ('deliberate', 'обдуманный', 'A deliberate choice.', 'Обдуманный выбор.', 'adj', ()),
    ('dilemma', 'дилемма', 'We face a dilemma.', 'Мы перед дилеммой.', 'noun', ()),
    ('empirical', 'эмпирический', 'Empirical evidence.', 'Эмпирические данные.', 'adj', ()),
    ('facilitate', 'облегчать', 'This tool facilitates work.', 'Этот инструмент облегчает работу.', 'verb', ()),
    ('hypothesis', 'гипотеза', 'Test the hypothesis.', 'Проверь гипотезу.', 'noun', ()),
    ('implication', 'последствие / подтекст', 'Consider the implications.', 'Учти последствия.', 'noun', ()),
    ('incentive', 'стимул', 'Financial incentives help.', 'Финансовые стимулы помогают.', 'noun', ()),
    ('integrity', 'честность / целостность', 'Act with integrity.', 'Действуй честно.', 'noun', ()),
    ('leverage', 'использовать / рычаг', 'Leverage your strengths.', 'Используй свои сильные стороны.', 'verb', ()),
    ('mandatory', 'обязательный', 'Attendance is mandatory.', 'Присутствие обязательно.', 'adj', ()),
    ('notwithstanding', 'несмотря на', 'Notwithstanding delays, we shipped.', 'Несмотря на задержки, мы выпустили.', 'prep', ()),
    ('objective', 'цель / объективный', 'Stay objective.', 'Будь объективным.', 'adj', ()),
    ('paradigm', 'парадigm', 'A new paradigm.', 'Новая парадigma.', 'noun', ()),
    ('persistent', 'настойчивый', 'Persistent effort pays off.', 'Настойчивость окупается.', 'adj', ()),
    ('plausible', 'правдоподобный', 'That sounds plausible.', 'Звучит правдоподобно.', 'adj', ()),
    ('preliminary', 'предварительный', 'Preliminary results look good.', 'Предварительные результаты хорошие.', 'adj', ()),
    ('proficient', 'опытный', 'She is proficient in English.', 'Она хорошо знает английский.', 'adj', ()),
    ('redundant', 'избыточный', 'This step is redundant.', 'Этот шаг избыточен.', 'adj', ()),
    ('reluctant', 'неохотный', 'He was reluctant to agree.', 'Он неохотно согласился.', 'adj', ()),
    ('resilience', 'устойчивость', 'Build resilience.', 'Развивай устойчивость.', 'noun', ()),
    ('scrutinize', 'тщательно проверять', 'Scrutinize the contract.', 'Тщательно проверь контракт.', 'verb', ()),
    ('substantial', 'существенный', 'A substantial improvement.', 'Существенное улучшение.', 'adj', ()),
    ('sustainable', 'устойчивый', 'Sustainable growth.', 'Устойчивый рост.', 'adj', ()),
    ('tangible', 'ощутимый', 'Tangible results.', 'Ощутимые результаты.', 'adj', ()),
    ('undermine', 'подрывать', 'Do not undermine trust.', 'Не подрывай доверие.', 'verb', ()),
    ('versatile', 'универсальный', 'A versatile tool.', 'Универсальный инструмент.', 'adj', ()),
    ('viable', 'жизнеспособный', 'Is it viable?', 'Это жизнеспособно?', 'adj', ()),
    ('advocate', 'отстаивать / сторонник', 'I advocate transparency.', 'Я за прозрачность.', 'verb', ()),
    ('allocate', 'распределять', 'Allocate resources wisely.', 'Распределяй ресурсы разумно.', 'verb', ()),
    ('benchmark', 'ориентир / эталон', 'Set a benchmark.', 'Задай ориентир.', 'noun', ()),
    ('compliance', 'соответствие', 'Ensure compliance.', 'Обеспечь соответствие.', 'noun', ()),
    ('consensus', 'консенсус', 'We reached consensus.', 'Мы достигли консенсуса.', 'noun', ()),
    ('contingency', 'запасной план', 'Have a contingency plan.', 'Имей запасной план.', 'noun', ()),
    ('correlate', 'коррелировать', 'These factors correlate.', 'Эти факторы коррелируют.', 'verb', ()),
    ('demographic', 'демографический', 'Demographic trends.', 'Демографические тренды.', 'adj', ()),
    ('discrepancy', 'расхождение', 'There is a discrepancy.', 'Есть расхождение.', 'noun', ()),
    ('elaborate', 'подробно объяснять', 'Can you elaborate?', 'Можешь подробнее?', 'verb', ()),
    ('feasible', 'осуществимый', 'Is it feasible?', 'Это осуществимо?', 'adj', ()),
    ('inherent', 'присущий', 'Inherent risks exist.', 'Есть присущие риски.', 'adj', ()),
    ('methodology', 'методология', 'Change the methodology.', 'Смени методологию.', 'noun', ()),
    ('paradox', 'парадокс', 'It is a paradox.', 'Это парадокс.', 'noun', ()),
    ('prerequisite', 'предварительное условие', 'Experience is a prerequisite.', 'Опыт — обязательное условие.', 'noun', ()),
    ('proactive', 'проактивный', 'Take a proactive approach.', 'Будь проактивным.', 'adj', ()),
    ('reconcile', 'согласовывать', 'Reconcile the numbers.', 'Согласуй цифры.', 'verb', ()),
    ('rigorous', 'строгий', 'Rigorous testing.', 'Строгое тестирование.', 'adj', ()),
    ('streamline', 'оптимизировать', 'Streamline the process.', 'Оптимизируй процесс.', 'verb', ()),
    ('transparency', 'прозрачность', 'We value transparency.', 'Мы ценим прозрачность.', 'noun', ()),
]

C1: list[tuple] = [
    ('acquiesce', 'соглашаться (неохотно)', 'He acquiesced to the plan.', 'Он неохотно согласился с планом.', 'verb', ()),
    ('ambivalent', 'неоднозначный', 'I feel ambivalent about it.', 'У меня неоднозначные чувства.', 'adj', ()),
    ('anomaly', 'аномалия', 'That result is an anomaly.', 'Этот результат — аномалия.', 'noun', ()),
    ('arcane', 'запутанный', 'Arcane regulations.', 'Запутанные правила.', 'adj', ()),
    ('articulate', 'чётко выражать', 'She articulates ideas well.', 'Она чётко выражает идеи.', 'verb', ()),
    ('astute', 'проницательный', 'An astute observer.', 'Проницательный наблюдатель.', 'adj', ()),
    ('circumspect', 'осмотрительный', 'Be circumspect in negotiations.', 'Будь осмотрителен на переговорах.', 'adj', ()),
    ('coalesce', 'объединяться', 'Ideas coalesced into a plan.', 'Идеи слились в план.', 'verb', ()),
    ('conjecture', 'предположение', 'That is mere conjecture.', 'Это лишь предположение.', 'noun', ()),
    ('contentious', 'спорный', 'A contentious topic.', 'Спорная тема.', 'adj', ()),
    ('corroborate', 'подтверждать', 'Data corroborates the claim.', 'Данные подтверждают утверждение.', 'verb', ()),
    ('culminate', 'завершаться', 'The project culminated in success.', 'Проект завершился успехом.', 'verb', ()),
    ('deference', 'уважение / почтение', 'Out of deference to her.', 'Из уважения к ней.', 'noun', ()),
    ('dichotomy', 'дихотомия', 'A false dichotomy.', 'Ложная дихотомия.', 'noun', ()),
    ('disseminate', 'распространять', 'Disseminate the findings.', 'Распространи результаты.', 'verb', ()),
    ('elusive', 'неуловимый', 'Success remained elusive.', 'Успех оставался неуловимым.', 'adj', ()),
    ('encompass', 'охватывать', 'The role encompasses many tasks.', 'Роль охватывает много задач.', 'verb', ()),
    ('ephemeral', 'мимолётный', 'Ephemeral trends.', 'Мимолётные тренды.', 'adj', ()),
    ('exacerbate', 'усугублять', 'This could exacerbate the issue.', 'Это может усугубить проблему.', 'verb', ()),
    ('exemplify', 'служить примером', 'This case exemplifies the rule.', 'Этот случай иллюстрирует правило.', 'verb', ()),
    ('formidable', 'внушительный', 'A formidable opponent.', 'Внушительный противник.', 'adj', ()),
    ('gratuitous', 'безосновательный', 'Gratuitous criticism.', 'Безосновательная критика.', 'adj', ()),
    ('hegemony', 'гегемония', 'Cultural hegemony.', 'Культурная гегемония.', 'noun', ()),
    ('impetus', 'импульс', 'The impetus for change.', 'Импульс к изменениям.', 'noun', ()),
    ('inadvertently', 'непреднамеренно', 'I inadvertently deleted it.', 'Я случайно удалил это.', 'adv', ()),
    ('incongruous', 'неуместный', 'An incongruous remark.', 'Неуместное замечание.', 'adj', ()),
    ('indigenous', 'коренной', 'Indigenous communities.', 'Коренные общины.', 'adj', ()),
    ('inference', 'вывод', 'Draw an inference.', 'Сделай вывод.', 'noun', ()),
    ('inherently', 'по своей сути', 'Inherently risky.', 'По сути рискованно.', 'adv', ()),
    ('juxtapose', 'сопоставлять', 'Juxtapose the two views.', 'Сопоставь два взгляда.', 'verb', ()),
    ('lucid', 'ясный', 'A lucid explanation.', 'Ясное объяснение.', 'adj', ()),
    ('meticulous', 'скrupulous', 'Meticulous planning.', 'Скрупулёзное планирование.', 'adj', ()),
    ('myriad', 'множество', 'A myriad of options.', 'Множество вариантов.', 'adj', ()),
    ('nascent', 'зарождающийся', 'A nascent market.', 'Зарождающийся рынок.', 'adj', ()),
    ('obfuscate', 'запутывать', 'Do not obfuscate the facts.', 'Не запутывай факты.', 'verb', ()),
    ('paradigmatic', 'парадigmatic', 'A paradigmatic example.', 'Парадigmaticный пример.', 'adj', ()),
    ('perfunctory', 'формальный', 'A perfunctory reply.', 'Формальный ответ.', 'adj', ()),
    ('pervasive', 'повсеместный', 'Pervasive influence.', 'Повсеместное влияние.', 'adj', ()),
    ('precarious', 'шаткий', 'A precarious situation.', 'Шаткая ситуация.', 'adj', ()),
    ('predilection', 'склонность', 'A predilection for detail.', 'Склонность к деталям.', 'noun', ()),
    ('prescient', 'предвидящий', 'A prescient forecast.', 'Предвидящий прогноз.', 'adj', ()),
    ('proliferate', 'быстро размножаться', 'Issues proliferated.', 'Проблемы размножились.', 'verb', ()),
    ('proviso', 'оговорка', 'With one proviso.', 'С одной оговоркой.', 'noun', ()),
    ('recalcitrant', 'непокорный', 'A recalcitrant stakeholder.', 'Непокорный стейкхолдер.', 'adj', ()),
    ('reconcile', 'примирять / согласовывать', 'Reconcile conflicting views.', 'Согласуй противоречивые взгляды.', 'verb', ()),
    ('reiterate', 'повторять', 'Let me reiterate.', 'Позволь повторить.', 'verb', ()),
    ('salient', 'важный', 'The salient points.', 'Ключевые моменты.', 'adj', ()),
    ('scrupulous', 'скrupulous', 'Scrupulous honesty.', 'Скрупулёзная честность.', 'adj', ()),
    ('substantiate', 'подкреплять', 'Substantiate your claim.', 'Подкрепи своё утверждение.', 'verb', ()),
    ('superfluous', 'лишний', 'Superfluous details.', 'Лишние детали.', 'adj', ()),
    ('surreptitious', 'тайный', 'A surreptitious glance.', 'Тайный взгляд.', 'adj', ()),
    ('tenuous', 'слабый', 'A tenuous connection.', 'Слабая связь.', 'adj', ()),
    ('ubiquitous', 'повсеместный', 'Ubiquitous technology.', 'Повсеместные технологии.', 'adj', ()),
    ('underscore', 'подчёркивать', 'This underscores the risk.', 'Это подчёркивает риск.', 'verb', ()),
    ('unequivocal', 'однозначный', 'An unequivocal answer.', 'Однозначный ответ.', 'adj', ()),
    ('veracity', 'правдивость', 'Doubt the veracity.', 'Сомневайся в правдивости.', 'noun', ()),
    ('vicarious', 'косвенный', 'Vicarious experience.', 'Косвенный опыт.', 'adj', ()),
    ('vociferous', 'громкий / настойчивый', 'Vociferous opposition.', 'Громкая оппозиция.', 'adj', ()),
]


def iter_builtin_rows() -> list[dict]:
    rows: dict[str, dict] = {}
    for level, pack in (
        ('a1', A1),
        ('a2', A2),
        ('b1', B1),
        ('b2', B2),
        ('c1', C1),
    ):
        for row in _pack(level, pack):
            rows[row['slug']] = row
    return list(rows.values())
