# Generated by Django 6.0.6 on 2026-07-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('study_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=30)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('original_text', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='study_app.useranswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='users_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation')], max_length=30)),
                ('score', models.FloatField(default=0.0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='users_app.userprofile')),
            ],
            options={
                'ordering': ['user', 'skill'],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill_progress')],
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('known', 'Known'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('strength', models.FloatField(default=0.0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to='users_app.userprofile')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.word')),
            ],
            options={
                'ordering': ['next_review_at', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'word'), name='unique_user_word_progress')],
            },
        ),
    ]
