# Generated by Django 6.0.6 on 2026-07-05 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_grammarrule'),
        ('progress_app', '0001_initial'),
        ('users_app', '0005_userprofile_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learned', 'Learned'), ('known', 'Already knew')], default='new', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rules', to='content_app.grammarrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rules', to='users_app.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'rule'), name='unique_user_rule')],
            },
        ),
    ]
